name: ensan_test
description: "تطبيق إنسان - تطبيق التبرعات الخيرية والإحسان"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.2.0
  
  # Development Tools
  device_preview: ^1.3.1
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & Networking
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Image Handling
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

  # Assets
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/